theme = "custom"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space.b]
d = ":buffer-close"
o = ":buffer-close-others"

[keys.normal]
C-s = ":write"
